# Site settings
title: Kommode-flow
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/kommode-flow" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  kommode

authors:
  pierre:
    display_name: Pierre Sköldborg
    email: pierre@kommode.se
  gustav_e:
    display_name: Gustav Eén
    email: gustav_e@kommode.se
  gustav_w:
    display_name: Gustav Wallner
    email: gustav_w@kommode.se
  erica:
    display_name: Erica Liljeblad
    email: erical@kommode.se
  marcus:
    display_name: Marcus Karlsson
    email: marcus@kommode.se
  gabriella:
    display_name: Gabriella Jonsson
    email: gabriella@kommode.se
  lars:
    display_name: Lars Haakon "Katt" Simonsen
    email: lars@kommode.se
    portrait: lars.jpg
  andreas:
    display_name: Andreas Sundström
    email: andreas@kommode.se
  martina:
    display_name: Martina Milisic
    email: martina@kommode.se

# Build settings
markdown: kramdown

paginate: 6
paginate_path: "page:num/"
